sudo: required

language: php

addons:
  sauce_connect: true
  apt:
    update: false
  chrome: stable
  artifacts:
    paths:
    - "./tests/_output/report.html"

cache:
  yarn: true
  directories:
  - "$HOME/.composer/cache"
  - vendor
  - node_modules

php:
- 7.2

dist: trusty

os: linux

git:
  depth: 1
  submodules: false

before_install:
- sudo apt-get update
- sudo apt-get install chromium-chromedriver
- phpenv config-rm xdebug.ini
- google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &

install:
- composer install --no-interaction
- yarn install --non-interactive --no-progress
- yarn run production
- php artisan storage:link
- php artisan key:generate --env=testing
- php artisan config:cache --env=testing
- php artisan serve --port=80 &

before_script:
- export PATH=$PATH:/usr/lib/chromium-browser/
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- sleep 3
- echo "Run chromedriver in background"
- chromedriver --url-base=/wd/hub &

script:
- php vendor/bin/codecept run --env=travis --verbose --fail-fast --html

after_script:
- sh -e /etc/init.d/xvfb stop

env:
  global:
  - secure: EiP9GA5mEJK+c1RsEuwb/WwDg1KqcLeBpOv/SulCXLyfHcFkoIbBPMHhvdZAjgjIpEn6Ea9q/xsLRUYr31Cd0pf4rBGPo9d3SlexHB+2PkJbbsTrRJp983UoogW7p/j/NwKZUYJsZvh+D1eNLl+8vw/CvkTUJg8zYvAQL18z1f9Mc/1pFoyQihM1nqN0gjvhtXClVPLB8062wmFKXvpfreqt7CaVpIwewfsv0YcgZWZYWodighR4BW+DNB1WfWTDqfZqPC0WL9OuK6kRRZlp0cxf30ynaoQTXfrlLzHqNEtO3BjufqtkmG+o3jf8XZNNAIKbP4Rycwz5XXR68P3BS9uV2iaOC96ME+RyosIibTgvZSGfV2kimrB54Ogj7VVqw9Y9P0703Mp2tk72rS9n9KnaeiE7qy1SpwJ2WfQcHn/8mWspm8FR1aR6yLLWuHKbJPB31MpGOC0J9u9CSYK0Z+EPvYQLb3+uu7MUvQUVWXYyVw8xvxxDQ47EZo7vPG/i9CTUYEVneFuFB8uh507BhQO08+iFQvbLzVghNfA9TFL18UrVk8jmDPXDRLenKmtggK73JgAGTUJZmH3vg5/G1xTUGh6XX26p2+G5m3+qqq6HWDIY+ZjOMAvNvpR15P0llNKh6FL3P/j3Sgb8YB7vUlzoXF+l38gdjtofjjMzx/I=
  - secure: hIpPzIPPfIw17gcV/viIq43YITPe7R6m5VjO1uJzQyOnBN54ueHJ1/itLvSteG3ExjapmPDbuC/0+IUqriF72iAT5cuGhBxduM+2RWjiHRfcIG58u6DEK77mwI1vJLyvL4YrrhZIgmOrHK+7+GpZgRDfFw+xSFeyeawcgqYbheLCMuEBCwvPtwR71DpHaW8iulFb0wzzyh58czL1pa1x1mmf5WefVXVVoDkFDmOO5lJmHw9DFDreOA34CzM5vWzU/FSZBYt8F38g6jRiUFseD8i16+4u+ZltUqhxZ7FfPsK8nAXwQmTakG+CFwa0j3WXLg1/bS2LZfcV4uYFhRS2WxGyXd9NW2iAHetr6f3sh9akEqJJI0Wgb/uiiG1+eU+PRbZRGzzQXCa0TDjJvTEGBSiuu2OlGXfo506d/ggypVKRBzNOtZEzub33xqpOMCZEZDsWNtjJHo4yxcTchtGObr0lr4gmUpI3b9WivDRTPbE4lsUjqNMA8IMJ7gA7H01jy7PPZG1rtIjbMa/shRQM30YeeM4wDR7N4R74aS3p5TLlMnSlVF0K/QSVtIlzMIxKqkOy24Vj+ANYam7vt6eXNFRAFVdBGYI1R00C2eM84x/I/VNUTRt5iyUpRvHo9lyP9gLZAKj+B4qiS+YT7p7RHkntrVjgHTqQRbe5e8bZUq4=
  - secure: zagztLFaFzPimclk5h+Ugb0zwmCTyQlh3dBdOGVoBuf2k5ggzJI58Z4rvMA2WfgmfeQpoAB6SS4nBSS5F+UNEQVlWXAdxFMs35wtSLMlhB9ZB+KXWXCZ1qgalLhUyk3Pz5syPYh8eifJGE9Jh+qitAyiTwfdAoZkX8KuubfKWYISyURKCOr5JCA1/CfTyIry0g+UsX5kwwHEPtQOUiVqvrYoz22PxKsM4VhX3nAv6fT9VMao2+BLAOxNaNWFMPrPY1t9TAGvNRuoUD+UiSloULXjtBJw57VSUKsBMCwl3ZHpActQ3UcdQiOjwYMmrOOcycd/2fuR0VJ1xi3aKE/dymkegSO5qZyt9kRumBqhLaq9bwJqqupYkhUAbr6D+3WrvXv92g5ycYEQpVOwMliLwgAtAllf66bVXqhZR0vhg3GAfvHcYcZmCajMPpdPMtzEJ6TLjGGJie+K7KbowHYx51KFsBI3LmBNK8iil92cef390b8R2Fon1ZsuF+ARxiACA50A5zschB5KN71g/1WGXIH0s7kS+wHoRztkX1VlEJYIwmC+cZF6dxXrVNp4QN1Wh6VT1u9wIWZ8fYxS4c4Sls72nHBfstJPmXT//+7gF726KrPP/6HpyBfIfce7UkR8Iuddiqgs2lpy1w0bLYH+1hy0q/8anijI3eanp7YfkxU=
  - secure: SNT4a6OVWrwZuMwRW6GosZ6UbLZlalYcTZm00eiUYOPOMugsmCkUU/zD0fVN5+MX9MfrjeiCNiWLtt1EvdRctmKD6C441+gEn+wpzi3HhIUYS/NZu+LvraN6uEBHSzh51+oeVhAnF4rGXNxCOeYcEPsOsRg/bUBCXsrQAxR1+Nt51eZpcSyobKtQYFnx2Boxb8WsYcOlIGNheFTUIo3m2fbTcQb8YJycoZUSfwZeWbuuFzx+Ie6LnWVDCH526Nvr7V264EaSyBzb0EkyMp+lO9zl33U5UtGROWKrSolPdayU4Gv9/reGokiOMtjylQs9ZgFdX5KG6GwnfJUwA3sz9/yPnwNQ8r1yuwOnx5Nlgt8jrojkiLSWyXwroHoXbTZDAIDaGBpROFCSW376a798QxcVY4l+CR8QxR7H8OUqPCOWvrGOSiU8Pu+xgUvLdqF5G0lqzXjFCoz4eh3Idivz+NRUmG/xgW/Svvqjadz8tYHZuN6T3au8QOyv+E3VD5ytGcxRkeSRTqx3HLsOAUnnLE367unDfI3jxlQECpjm0/XpTJzvSMZekrlS+ofkIEaeMdaxrB/hfO+eHZqysSQg6m3zBAe/3Vp5zUWUVOuQgTiIHlxxdsiYJ+EL6EXvCXcwKVXcVpuOpCbn/ULRYxzQ6dt2jRL5ElCXppnNYlo2VUc=
  - secure: czIuIPemnkCtWVdAiWYr6cE97LLe+3ujofaqt67Up7N5qpO8GVYASOgqIE8lt+Ljn7ZTqqDbdcgsyLlUrXMpBYm5xwFZDa01IEYSGwKrs3j55GoiuBHNoWkvCDe4zHcUb9NFGn5WKRexVRnTadCRaK5s3JnvZb0QEOoyxbotQqRH+QD14nK9KJZjlor5lQMUn4qe5aZOAoS+0oO/7xQUKxUOmKu60TTnx9tW0jgLOr6bNSYqRwhFu4eu1Tpz6P2c6/g+bKZS36OHYctNcL59yYW6ThsxO1i0F67DwLutjlSzyyGlTlPgrHQ27STMY+xZjXRX5AOL/lTlA1N4qr2AuVcysi7YDyygyTYxYskIiNq458NgEDsPRim/lpHq/Q4Vws5CCh0QcrimssP8wR9ebBlOiv1NuwH3EATWNwJXNqXl6QLISTlbuq2YB6Ms6GFiTiz3SCbcTfnzGESzHMK40Kki98sZnmvcy5c/wVZKbicVo7VImOMUW+CTIMf6cSeQbw/SyHHwk2g5GFlj8QxcdQe9MUXJ1z9iIXp/dbqHYxAumQpOibZEKbBbG/w1MCgE0SLqNA0QmnADfGv7/l++JG6Zwl2cvuL03cq2L0VZM6Msl+23pDaslmj/zEa5OatPv6RN2fLs3u4nK3Tzdbi7mrTDI8be4AAeZoL2IT3as64=
  - secure: eJ6pD7zhHLQmT+UAbbM6nnBwf5lvFG7kT4xZRieXom83Kx2zG8MwgjXXExuXzWgOfbOxRWLJ8VD7xcO8cH1mMLllZIoLX2F1Pd1x8LdUB8hgqcq5fhr4w0uIzIJ8FCnYvDP/n57YcnZbzCTNxMQcS/gLBq82WAuGpxLcpAcfQjJ4deYZpvmJgQQjnFI5pQBpJ9psFrJGaicN6XULN/xff1AgvMZUSAnvaY0MKc9gn0NQV/lLO9ZOkMrcLk2GC6nBtGE/kv/M2kQAbep4lDfavh/uj2SFjHc2TyWqaUzzQp4MjZGTGR672XNcpworiCa58RGF8+j9hZb5jYH0WbB954ltFH89Xn3PCfElaSPn/xJfHk5ph8DrIcXBbEsvxMxenBCrknMDJQsYn+6j1YfKUET1QA7fY+683HoFVW3NXSM0AXodbwJjrB6LKTnRD+WYOS6HBkHJSxTXrzd5k+pdwj5d0t5YblMTWH3URVwAkwGsmSLj1spfHpSFY/6YSNcw1VnjogBZuCwzwjoSwJNXvvI2ZJQvgQod22Gdf3mf3ltNA8W4tXYZVsDNC3aLOvZDw6aHysMTttzbZIdsQ6FzW3kkILGsXtjwBjueHZJGxMwcRl7VZDeAAK9/QSlzcOWOMqn0WDX9K8XPpg2xD0wooBQV2xWbA3QVFmIWq8Lenk0=
  - secure: GifQzQUHMKy/To6Q/2N7JYfFD/LafCOLeDW8Qprd2vJQTRjRWYNUuuHtKIYhT7fmeJj7nd7/NqpbK6iIuv9ZuFJEXo+kTLSno+bUHykaeg2FGGQtNlKDaXQosCmq4vBeYTon19x1weBYqW6KgcooiVYCdwKbvSdANY340o+jrOuKr2U6lJfCy2ZW3SWlkQ+S57OJwyWOPwWjYUEH54IJv3tToZD5RA1HjL2kcDvuVsLIZPpuJ/MZZU9jJ8QBmZdZlK6QCwGtR+rydA+HR0ggA4GzKWBw/uJkJ5JFlY2bE1yiUEk+K0Lv4/lRh6spNUt/EkdprCViA81AZOhakYalF86IrQXYyJzszOmYe5fl7BlDfgm1d/CYGL+YKbD5Qyt9w1sPP86SVMQMoOlm++1WD3TU67oonQZei1HOBXZrJWEOyOCbIcrutQk5iZeUx7hlbylSV34RoPtgQZzls5AJADi5wRQtO/uCYMqUrwsRo6uK3OiEFyXzo/5Bg3SpnPuWyz5YYeX8/fyoroFnxdxo8oUMZp1+8WeeGAHV3DpX5MebkieC5BDR2FYhBLFStszLlbDaw73bgqg9em4j8an18JAkgwrYy6kayPS70611ovVsxvEhu3QRFOYfhhH2F1c461Hd0vAO1VGgnDLyclaoGb4Zsub9j1AftQp9DO5Scfs=
