sudo: false
language: php
addons:
  artifacts:
    paths:
    - "./tests/_output/report.html"
cache:
  yarn: true
  directories:
  - "$HOME/.composer/cache"
  - vendor
  - node_modules
php:
- 7.1
dist: trusty
os: linux
git:
  depth: 1
  submodules: false
before_install:
- php -v
- php -m
- alias composer="php-n -d memory_limit=-1 $(which composer)"
- travis_retry composer self-update --stable
- travis_retry composer update --prefer-dist --no-interaction --no-suggest --no-plugins
script:
- "$(which php) vendor/bin/codecept run --verbose --fail-fast --html"
env:
  global:
  - secure: EiP9GA5mEJK+c1RsEuwb/WwDg1KqcLeBpOv/SulCXLyfHcFkoIbBPMHhvdZAjgjIpEn6Ea9q/xsLRUYr31Cd0pf4rBGPo9d3SlexHB+2PkJbbsTrRJp983UoogW7p/j/NwKZUYJsZvh+D1eNLl+8vw/CvkTUJg8zYvAQL18z1f9Mc/1pFoyQihM1nqN0gjvhtXClVPLB8062wmFKXvpfreqt7CaVpIwewfsv0YcgZWZYWodighR4BW+DNB1WfWTDqfZqPC0WL9OuK6kRRZlp0cxf30ynaoQTXfrlLzHqNEtO3BjufqtkmG+o3jf8XZNNAIKbP4Rycwz5XXR68P3BS9uV2iaOC96ME+RyosIibTgvZSGfV2kimrB54Ogj7VVqw9Y9P0703Mp2tk72rS9n9KnaeiE7qy1SpwJ2WfQcHn/8mWspm8FR1aR6yLLWuHKbJPB31MpGOC0J9u9CSYK0Z+EPvYQLb3+uu7MUvQUVWXYyVw8xvxxDQ47EZo7vPG/i9CTUYEVneFuFB8uh507BhQO08+iFQvbLzVghNfA9TFL18UrVk8jmDPXDRLenKmtggK73JgAGTUJZmH3vg5/G1xTUGh6XX26p2+G5m3+qqq6HWDIY+ZjOMAvNvpR15P0llNKh6FL3P/j3Sgb8YB7vUlzoXF+l38gdjtofjjMzx/I=
  - secure: hIpPzIPPfIw17gcV/viIq43YITPe7R6m5VjO1uJzQyOnBN54ueHJ1/itLvSteG3ExjapmPDbuC/0+IUqriF72iAT5cuGhBxduM+2RWjiHRfcIG58u6DEK77mwI1vJLyvL4YrrhZIgmOrHK+7+GpZgRDfFw+xSFeyeawcgqYbheLCMuEBCwvPtwR71DpHaW8iulFb0wzzyh58czL1pa1x1mmf5WefVXVVoDkFDmOO5lJmHw9DFDreOA34CzM5vWzU/FSZBYt8F38g6jRiUFseD8i16+4u+ZltUqhxZ7FfPsK8nAXwQmTakG+CFwa0j3WXLg1/bS2LZfcV4uYFhRS2WxGyXd9NW2iAHetr6f3sh9akEqJJI0Wgb/uiiG1+eU+PRbZRGzzQXCa0TDjJvTEGBSiuu2OlGXfo506d/ggypVKRBzNOtZEzub33xqpOMCZEZDsWNtjJHo4yxcTchtGObr0lr4gmUpI3b9WivDRTPbE4lsUjqNMA8IMJ7gA7H01jy7PPZG1rtIjbMa/shRQM30YeeM4wDR7N4R74aS3p5TLlMnSlVF0K/QSVtIlzMIxKqkOy24Vj+ANYam7vt6eXNFRAFVdBGYI1R00C2eM84x/I/VNUTRt5iyUpRvHo9lyP9gLZAKj+B4qiS+YT7p7RHkntrVjgHTqQRbe5e8bZUq4=
  - secure: zagztLFaFzPimclk5h+Ugb0zwmCTyQlh3dBdOGVoBuf2k5ggzJI58Z4rvMA2WfgmfeQpoAB6SS4nBSS5F+UNEQVlWXAdxFMs35wtSLMlhB9ZB+KXWXCZ1qgalLhUyk3Pz5syPYh8eifJGE9Jh+qitAyiTwfdAoZkX8KuubfKWYISyURKCOr5JCA1/CfTyIry0g+UsX5kwwHEPtQOUiVqvrYoz22PxKsM4VhX3nAv6fT9VMao2+BLAOxNaNWFMPrPY1t9TAGvNRuoUD+UiSloULXjtBJw57VSUKsBMCwl3ZHpActQ3UcdQiOjwYMmrOOcycd/2fuR0VJ1xi3aKE/dymkegSO5qZyt9kRumBqhLaq9bwJqqupYkhUAbr6D+3WrvXv92g5ycYEQpVOwMliLwgAtAllf66bVXqhZR0vhg3GAfvHcYcZmCajMPpdPMtzEJ6TLjGGJie+K7KbowHYx51KFsBI3LmBNK8iil92cef390b8R2Fon1ZsuF+ARxiACA50A5zschB5KN71g/1WGXIH0s7kS+wHoRztkX1VlEJYIwmC+cZF6dxXrVNp4QN1Wh6VT1u9wIWZ8fYxS4c4Sls72nHBfstJPmXT//+7gF726KrPP/6HpyBfIfce7UkR8Iuddiqgs2lpy1w0bLYH+1hy0q/8anijI3eanp7YfkxU=
  - secure: IUtTek49JFrj7jVrj3WgLF0DpOVbB6zT9IAl/uenrkKlO93eClKFMhWX+qrsqrNxqJ7tsQeMnEA0JEn7ElUPINsrC369+EJA9So0wyUSWJGGgL6/Hy+kejdAKEFUWc19MfogL9gvpAkmSWZxQyozPtItgw9Smgq6X9P8hwOCYXnOsgLl8P2eE24w6KRv72zRtNOIg6kNhozphJ0lfiIUv5Sd0RELCr51vXdPQqAP8bDvtAduHnSro0QTWZ5DglY62q1POj3+5lhhqA/RVK9co/IL6PT6Ji7K7mssoa1J7qFty+hkPXc/UtPlHBDlcFtd1UT8rYuNORdtic5TDgFo46jZok7g9JhntHaCcsbGVljAb2Zl4i0Uw5YW+GZx+Ohbs4GxP8k5o0MkyS+ts6qmFQOMzfWj+q6/ZWMIaTgswt2X9KJHc/wbHmlpWfM+3dxZDNV7uRIRdydQ+DpmXJ49QNundByhkHBoedUb4R9GEOLj9b3fnGBrkn6/XMV8S2N09op51LYvpzhr/fXNYh5UAD3mZx++BJPg5F3lo8O7wndjTML/TH1AntvAbodUxz6K96yDzN7RdWPq/yYooQEZ/EydwUAv6JS5y0xAXj0/NphPfI6aPQBZsTZtazPrFgTZPviGHtmQkvHuC5qjB5JoYJZ2yIunFKzn3xtabdCstkY=
